language: java
jdk:
  - oraclejdk12
  - openjdk12

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

dist: trusty

addons:
  sonarcloud:
    organization: "alexlrodrigues"
    token:
      secure: "3d1d64ed8d5da415e512bf7d22402e3d59b8757d"
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

#deploy:
#  provider: heroku
#  api_key:
#    secure: f4240002-22d7-4438-8e77-074aebc5556f
#  app: dna-base-search
#  on:
#    repo: AlexLRodrigues/dna_base_search