language: java
jdk:
  - oraclejdk12
  - openjdk12

cache:
  directories:
    - $HOME/.m2

dist: trusty

addons:
  sonarcloud:
    organization: "alexlrodrigues"
    token:
      secure: "0e922d49c65e6b822ab4aa44c6796aeb8c13c741"
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlexLRodrigues_dna_base_search